// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Component1: typeof import('./src/components/component1.vue')['default']
    Component2: typeof import('./src/components/component2.vue')['default']
    Deep: typeof import('./src/components/deep.vue')['default']
  }
}

export { }
